version: '2'
services:
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=analysis
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Japan
    networks:
      - default
    ports:
      - '3306:3306'
  jupyter:
    build: jupyter
    volumes:
      - ./jupyter/:/home/jovyan/work/
    ports:
      - '8888:8888'
  web:
    build: .
    volumes:
      - .:/usr/src/app/
    networks:
      - default
    ports:
      - "8000:8000"
    depends_on:
      - db
      - jupyter
    environment:
      - TZ=Japan
    tty: true